--DISABLE TRIGGER AUD_LOGON_DATABSE
CREATE OR REPLACE PROCEDURE admin1.DIS_AUD_LOGON
AUTHID CURRENT_USER
AS
BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER AUD_LOGON_DATABASE DISABLE';
END;
/

--DISABLE AUDIT HOSOBENHAN
CREATE OR REPLACE PROCEDURE admin1.DIS_AUD_HOSOBENHAN
AUTHID CURRENT_USER
AS
BEGIN
        SYS.DBMS_FGA.DISABLE_POLICY(
            OBJECT_SCHEMA => 'admin1',
            OBJECT_NAME => 'HOSOBENHAN',
            POLICY_NAME => 'AUDIT_ILLEGAL_ALTER_HOSOBENHAN');
END;
/

--DISABLE AUDIT DONTHUOC
CREATE OR REPLACE PROCEDURE admin1.DIS_AUD_DONTHUOC
AUTHID CURRENT_USER
AS
BEGIN
    BEGIN
        SYS.DBMS_FGA.DISABLE_POLICY(
            OBJECT_SCHEMA => 'admin1',
            OBJECT_NAME => 'DONTHUOC',
            POLICY_NAME => 'AUDIT_ILLEGAL_ALTER_DONTHUOC');
    END;
END;
/
------------------------------ENABLE--------------------------------------
--ENABLE TRIGGER AUD_LOGON_DATABSE
CREATE OR REPLACE PROCEDURE admin1.EN_AUD_LOGON
AUTHID CURRENT_USER
AS
BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER AUD_LOGON_DATABASE ENABLE';
END;
/

--ENABLE AUDIT HOSOBENHAN
CREATE OR REPLACE PROCEDURE admin1.EN_AUD_HOSOBENHAN
AUTHID CURRENT_USER
AS
BEGIN
    BEGIN
        SYS.DBMS_FGA.ENABLE_POLICY(
            OBJECT_SCHEMA => 'admin1',
            OBJECT_NAME => 'HOSOBENHAN',
            POLICY_NAME => 'AUDIT_ILLEGAL_ALTER_HOSOBENHAN');
    END;
END;
/

--ENABLE AUDIT DONTHUOC
CREATE OR REPLACE PROCEDURE admin1.EN_AUD_DONTHUOC
AUTHID CURRENT_USER
AS
BEGIN
    BEGIN
        SYS.DBMS_FGA.ENABLE_POLICY(
            OBJECT_SCHEMA => 'admin1',
            OBJECT_NAME => 'DONTHUOC',
            POLICY_NAME => 'AUDIT_ILLEGAL_ALTER_DONTHUOC');
    END;
END;
/