--TRIGGER DE LAY IP NGUOI DUNG
CREATE OR REPLACE TRIGGER admin1.SET_IP_IN_ID
AFTER LOGON ON DATABASE
BEGIN
    dbms_session.set_identifier (SYS_CONTEXT('USERENV','IP_ADDRESS'));
END;
/

--TABLE LUU THONG TIN AUDIT LOGON RIENG
CREATE TABLE admin1.AUD_LOGON(
    USERNAME VARCHAR(10),
    USER_IP VARCHAR(20),
    DATETIME DATE DEFAULT SYSDATE
);
/

--TRIGGER AUDIT LOGON RIENG
CREATE OR REPLACE TRIGGER admin1.AUD_LOGON_DATABASE
AFTER LOGON ON DATABASE
BEGIN
    INSERT INTO admin1.AUD_LOGON VALUES (SYS_CONTEXT('USERENV','SESSION_USER'),SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),SYSDATE);
END;
/

--AUDIT FGA AUDIT SU THAY DOI TRAI PHEP CUA BANG HOSOBENHAN
BEGIN
    DBMS_FGA.ADD_POLICY(
        OBJECT_SCHEMA => 'ADMIN1',
        OBJECT_NAME => 'HOSOBENHAN',
        POLICY_NAME => 'AUDIT_ILLEGAL_ALTER_HOSOBENHAN',
        AUDIT_CONDITION => 'MABS!=USER',
        AUDIT_COLUMN => 'TRIEUCHUNG,KETLUAN'
    );
END;
/

/*BEGIN
    DBMS_FGA.DROP_POLICY (OBJECT_SCHEMA => 'admin1',
       OBJECT_NAME => 'DONTHUOC',
       POLICY_NAME => 'AUDIT_ILLEGAL_ALTER_DONTHUOC');
END;*/

--AUDIT FGA AUDIT SU THAY DOI TRAI PHEP CUA BANG DONTHUOC
BEGIN
    DBMS_FGA.ADD_POLICY(
        OBJECT_SCHEMA => 'ADMIN1',
        OBJECT_NAME => 'DONTHUOC',
        POLICY_NAME => 'AUDIT_ILLEGAL_ALTER_DONTHUOC',
        AUDIT_CONDITION => 'MABS!=USER'
    );
END;
/

--AUDIT FGA AUDIT SU THAY DOI TRAI PHEP CUA BANG CHITIETDONTHUOC
BEGIN
    DBMS_FGA.ADD_POLICY(
        OBJECT_SCHEMA => 'admin1',
        OBJECT_NAME => 'CHITIETDONTHUOC',
        POLICY_NAME => 'AUDIT_ILLEGAL_ALTER_CHITIETDONTHUOC'
    );
END;
/

